import { escapeHtml } from "./template-helpers";
import type { IndividualWorker } from "@shared/types";

/**
 * worker-templates.ts
 * Single Responsibility: Generates executive HTML email markup for Individual Worker Registry enrollments.
 */

export function renderAdminWorkerEmail(
  worker: IndividualWorker,
  settings: Record<string, string>,
  adminBaseUrl: string = "http://localhost:3001"
): { html: string; text: string; subject: string } {
  const companyName = (settings.company_name || "Dezoryn Contractor").trim();
  const safeName = escapeHtml(worker.fullName);
  const safePhone = escapeHtml(worker.phone);
  const safeTrade = escapeHtml(worker.trade);
  const safeLocation = escapeHtml(`${worker.currentCity}, ${worker.currentState}`);
  const safeWage = escapeHtml(worker.dailyWageExpect || "Standard Daily Rate");
  const regDate = new Date(worker.createdAt || Date.now()).toLocaleString("en-IN", {
    timeZone: "Asia/Kolkata",
    dateStyle: "medium",
    timeStyle: "short",
  });

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>New Artisan Enrolled - ${worker.workerCode}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0f172a; color: #334155; margin: 0; padding: 24px 0; }
    .wrapper { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.15); border: 1px solid #e2e8f0; }
    .header { background: #090d16; padding: 24px 30px; border-bottom: 3px solid #2563eb; }
    .header-tag { font-size: 11px; font-weight: 800; color: #60a5fa; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 4px; }
    .header h1 { margin: 0; font-size: 18px; color: #ffffff; font-weight: 700; }
    .content { padding: 28px 30px; }
    .grid-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13.5px; }
    .grid-table th { text-align: left; padding: 9px 12px; background: #f8fafc; color: #64748b; font-weight: 600; font-size: 12px; text-transform: uppercase; border-bottom: 1px solid #e2e8f0; width: 35%; }
    .grid-table td { padding: 9px 12px; border-bottom: 1px solid #f1f5f9; color: #0f172a; font-weight: 500; }
    .action-btn { display: inline-block; background: #0f172a; color: #ffffff !important; text-decoration: none; padding: 10px 20px; border-radius: 4px; font-weight: 700; font-size: 13px; }
    .footer { background: #f8fafc; padding: 18px 30px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; text-align: center; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <div class="header-tag">${escapeHtml(companyName)} Artisan Registry</div>
      <h1>New Direct Worker Enrollment</h1>
    </div>
    <div class="content">
      <p style="margin: 0 0 16px 0; font-size: 14px; color: #475569;">
        A skilled artisan has registered for highway deployment in the skill pool.
      </p>

      <table class="grid-table">
        <tr>
          <th>Worker Code</th>
          <td><strong>${escapeHtml(worker.workerCode)}</strong></td>
        </tr>
        <tr>
          <th>Artisan Name</th>
          <td><strong>${safeName}</strong></td>
        </tr>
        <tr>
          <th>Primary Trade</th>
          <td><strong style="color: #2563eb;">${safeTrade}</strong></td>
        </tr>
        <tr>
          <th>Experience</th>
          <td>${worker.experienceYears} Years</td>
        </tr>
        <tr>
          <th>Phone Number</th>
          <td><a href="tel:${safePhone}" style="color: #c9a35d; font-weight: 700; text-decoration: none;">${safePhone}</a></td>
        </tr>
        <tr>
          <th>Location</th>
          <td>${safeLocation}</td>
        </tr>
        <tr>
          <th>Daily Wage Expectation</th>
          <td>${safeWage}</td>
        </tr>
        <tr>
          <th>Willing to Relocate</th>
          <td>${worker.canRelocate ? "Yes (Pan-India / Inter-State)" : "Local Sites Only"}</td>
        </tr>
        <tr>
          <th>Registered At</th>
          <td>${regDate}</td>
        </tr>
      </table>

      <div style="text-align: center; margin: 24px 0 8px 0;">
        <a href="${adminBaseUrl}" class="action-btn">
          View in Worker Registry →
        </a>
      </div>
    </div>
    <div class="footer">
      Automated notification generated by ${escapeHtml(companyName)} Control System.
    </div>
  </div>
</body>
</html>
  `;

  return {
    subject: `[Worker #${worker.workerCode}] ${worker.fullName} (${worker.trade} • ${worker.experienceYears}y exp)`,
    html,
    text: `New Worker Registered: ${worker.fullName} (${worker.workerCode})\nTrade: ${worker.trade}\nExperience: ${worker.experienceYears} Years\nPhone: ${worker.phone}\nLocation: ${worker.currentCity}, ${worker.currentState}`,
  };
}
